# FROM almalinux:9 
# ENV course="Devops" \
#     trainer="siva" \
#     duration="120"
# RUN echo "Hello ${trainer}" > /tmp/devops.txt
# CMD ["sleep", "100"]


FROM almalinux:9 
ARG USERNAME=sivakumar
RUN echo "Hello ${USERNAME}" > /tmp/devops.txt
CMD ["sleep", "100"]